version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/app/build
    ports:
      - "3000:80" 

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/app/static
    ports:
      - "8000:80" 
    depends_on:
      - frontend
